### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by leonboe1** [alanesq/esp32cam-demo#3]
Hi, I would like to use your code as a start for my (open-source) project. Am I allowed to use the code and publish a modified version? I'm asking because I couldn't find any license information on the project page. Maybe you could add a MIT License or something comparable?

Thanks for answering,
Leon

**Comment by alanesq** [comment]
Thanks for asking

Yes, you are free to use any of it, glad it is of help/use.

I think I have just added a licence to it (I am not very experienced using Github)

**Comment by leonboe1** [comment]
That's awesome! Keep up the good work!
