### ISSUE TITLE
Add ability for AM312 motion sensor on pin 13

### ISSUE THREAD

**Issue by 91JJ** [alanesq/esp32cam-demo#4]
Reading through the config it says pin 13 is free.
Can you add the ability for a motion sensor to trigger a picture via that pin?

**Comment by alanesq** [comment]
Yes, in the sketch I have it set as an output pin but no reason it can't be used for input instead
12 is also available but if it is pulled high it will prevent the esp32cam from booting

**Comment by 91JJ** [comment]
> Yes, in the sketch I have it set as an output pin but no reason it can't be used for input instead 12 is also available but if it is pulled high it will prevent the esp32cam from booting

Thanks!
I did notice that and tried it. I changed the pin to input mode but the motion sensor is always "high"

**Comment by alanesq** [comment]
Hi,
I have just modified the sketch so that pin 12 is output and pin 13 is input
I have tested it and the input pin is working ok
BTW - You may need to use a pulldown resistor (or enable it via software)?

**Comment by 91JJ** [comment]
Hi @alanesq,
I've been testing this out via yaml as I'm a little more familiar with that and I think your right!
pin 13 needs to be set to 'PULLDOWN'

Is it possible to edit this or make it configurable within the code? (similar to the below)

`   //#if defined(CAMERA_MODEL_ESP_EYE)
   //  pinMode(13, INPUT_PULLUP);
   //  pinMode(14, INPUT_PULLUP);
   //#endif`

**Comment by alanesq** [comment]
This is set in "setup" and would need to be changed depending on what the pins are to be used for

**Comment by 91JJ** [comment]
I think the ESP32-CAM-MB has built in resistors (could be wrong) and needed for pin 13 using the AM312.

Arduino doesn't support 'INPUT_PULLDOWN' which works when using ESPHome/Yaml.

Not sure how to use code to stop the sensor showing "High" constantly.
